<a href="https://colab.research.google.com/github/Shivamani162/GEN-AI/blob/main/Copy_of_Lab_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.metrics import mean_squared_error

# Actual and predicted values
y_actual = np.array([20, 30, 40, 50])
y_pred = np.array([20.5, 30.3, 40.2, 50.6])

# Calculate MSE from scratch
mse_manual = np.sum((y_actual - y_pred) ** 2) / len(y_actual)

# Calculate MSE using sklearn
mse_library = mean_squared_error(y_actual, y_pred)

# Print results
print(f"MSE calculated manually: {mse_manual}")
print(f"MSE using library: {mse_library}")


MSE calculated manually: 0.18500000000000083
MSE using library: 0.18500000000000083


In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error

# Actual and predicted values
y_actual = np.array([20, 30, 40, 50])
y_pred = np.array([20.5, 30.3, 40.2, 50.6])

# Calculate MAE from scratch
mae_manual = np.sum(np.abs(y_actual - y_pred)) / len(y_actual)

# Calculate MAE using sklearn
mae_library = mean_absolute_error(y_actual, y_pred)

# Print results
print(f"MAE calculated manually: {mae_manual}")
print(f"MAE using library: {mae_library}")


MAE calculated manually: 0.40000000000000124
MAE using library: 0.40000000000000124


In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Actual and predicted values
y_actual = np.array([20, 30, 40, 50])
y_pred = np.array([20.5, 30.3, 40.2, 50.6])

# Calculate MAE from scratch
mae_manual = np.sum(np.abs(y_actual - y_pred)) / len(y_actual)

# Calculate MAE using sklearn
mae_library = mean_absolute_error(y_actual, y_pred)

# Calculate RMSE from scratch
rmse_manual = np.sqrt(np.sum((y_actual - y_pred) ** 2) / len(y_actual))

# Calculate RMSE using sklearn
rmse_library = np.sqrt(mean_squared_error(y_actual, y_pred))

# Print results
print(f"MAE calculated manually: {mae_manual}")
print(f"MAE using library: {mae_library}")
print(f"RMSE calculated manually: {rmse_manual}")
print(f"RMSE using library: {rmse_library}")


MAE calculated manually: 0.40000000000000124
MAE using library: 0.40000000000000124
RMSE calculated manually: 0.4301162633521323
RMSE using library: 0.4301162633521323


In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, confusion_matrix, accuracy_score

# Actual and predicted values for regression
y_actual = np.array([20, 30, 40, 50])
y_pred = np.array([20.5, 30.3, 40.2, 50.6])

# Calculate MAE from scratch
mae_manual = np.sum(np.abs(y_actual - y_pred)) / len(y_actual)

# Calculate MAE using sklearn
mae_library = mean_absolute_error(y_actual, y_pred)

# Calculate RMSE from scratch
rmse_manual = np.sqrt(np.sum((y_actual - y_pred) ** 2) / len(y_actual))

# Calculate RMSE using sklearn
rmse_library = np.sqrt(mean_squared_error(y_actual, y_pred))

# Actual and predicted values for classification
y_actual_cls = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
y_pred_cls = np.array([0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2])

# Compute confusion matrix manually
num_classes = len(np.unique(y_actual_cls))
conf_matrix = np.zeros((num_classes, num_classes), dtype=int)
for a, p in zip(y_actual_cls, y_pred_cls):
    conf_matrix[a, p] += 1

# Compute confusion matrix using sklearn
conf_matrix_lib = confusion_matrix(y_actual_cls, y_pred_cls)

# Compute accuracy manually
accuracy_manual = np.sum(np.diag(conf_matrix)) / len(y_actual_cls)

# Compute accuracy using sklearn
accuracy_lib = accuracy_score(y_actual_cls, y_pred_cls)

# Print results
print(f"MAE calculated manually: {mae_manual}")
print(f"MAE using library: {mae_library}")
print(f"RMSE calculated manually: {rmse_manual}")
print(f"RMSE using library: {rmse_library}")
print("Confusion Matrix calculated manually:")
print(conf_matrix)
print("Confusion Matrix using library:")
print(conf_matrix_lib)
print(f"Accuracy calculated manually: {accuracy_manual}")
print(f"Accuracy using library: {accuracy_lib}")


MAE calculated manually: 0.40000000000000124
MAE using library: 0.40000000000000124
RMSE calculated manually: 0.4301162633521323
RMSE using library: 0.4301162633521323
Confusion Matrix calculated manually:
[[2 1 2]
 [2 1 2]
 [2 1 2]]
Confusion Matrix using library:
[[2 1 2]
 [2 1 2]
 [2 1 2]]
Accuracy calculated manually: 0.3333333333333333
Accuracy using library: 0.3333333333333333


In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, confusion_matrix, accuracy_score

# Actual and predicted values for regression
y_actual = np.array([20, 30, 40, 50])
y_pred = np.array([20.5, 30.3, 40.2, 50.6])

# Calculate MAE from scratch
mae_manual = np.sum(np.abs(y_actual - y_pred)) / len(y_actual)

# Calculate MAE using sklearn
mae_library = mean_absolute_error(y_actual, y_pred)

# Calculate RMSE from scratch
rmse_manual = np.sqrt(np.sum((y_actual - y_pred) ** 2) / len(y_actual))

# Calculate RMSE using sklearn
rmse_library = np.sqrt(mean_squared_error(y_actual, y_pred))

# Actual and predicted values for classification (Table 5)
y_actual_cls = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
y_pred_cls = np.array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1])

# Compute confusion matrix manually
num_classes = len(np.unique(y_actual_cls))
conf_matrix = np.zeros((num_classes, num_classes), dtype=int)
for a, p in zip(y_actual_cls, y_pred_cls):
    conf_matrix[a, p] += 1

# Compute confusion matrix using sklearn
conf_matrix_lib = confusion_matrix(y_actual_cls, y_pred_cls)

# Compute accuracy manually
accuracy_manual = np.sum(np.diag(conf_matrix)) / len(y_actual_cls)

# Compute accuracy using sklearn
accuracy_lib = accuracy_score(y_actual_cls, y_pred_cls)

# Print results
print(f"MAE calculated manually: {mae_manual}")
print(f"MAE using library: {mae_library}")
print(f"RMSE calculated manually: {rmse_manual}")
print(f"RMSE using library: {rmse_library}")
print("Confusion Matrix calculated manually:")
print(conf_matrix)
print("Confusion Matrix using library:")
print(conf_matrix_lib)
print(f"Accuracy calculated manually: {accuracy_manual}")
print(f"Accuracy using library: {accuracy_lib}")


MAE calculated manually: 0.40000000000000124
MAE using library: 0.40000000000000124
RMSE calculated manually: 0.4301162633521323
RMSE using library: 0.4301162633521323
Confusion Matrix calculated manually:
[[3 2]
 [2 3]]
Confusion Matrix using library:
[[3 2]
 [2 3]]
Accuracy calculated manually: 0.6
Accuracy using library: 0.6


In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, confusion_matrix, accuracy_score, recall_score

# Actual and predicted values for regression
y_actual = np.array([20, 30, 40, 50])
y_pred = np.array([20.5, 30.3, 40.2, 50.6])

# Calculate MAE from scratch
mae_manual = np.sum(np.abs(y_actual - y_pred)) / len(y_actual)

# Calculate MAE using sklearn
mae_library = mean_absolute_error(y_actual, y_pred)

# Calculate RMSE from scratch
rmse_manual = np.sqrt(np.sum((y_actual - y_pred) ** 2) / len(y_actual))

# Calculate RMSE using sklearn
rmse_library = np.sqrt(mean_squared_error(y_actual, y_pred))

# Actual and predicted values for classification (Table 7)
y_actual_cls = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
y_pred_cls = np.array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1])

# Compute confusion matrix manually
num_classes = len(np.unique(y_actual_cls))
conf_matrix = np.zeros((num_classes, num_classes), dtype=int)
for a, p in zip(y_actual_cls, y_pred_cls):
    conf_matrix[a, p] += 1

# Compute confusion matrix using sklearn
conf_matrix_lib = confusion_matrix(y_actual_cls, y_pred_cls)

# Compute accuracy manually
accuracy_manual = np.sum(np.diag(conf_matrix)) / len(y_actual_cls)

# Compute accuracy using sklearn
accuracy_lib = accuracy_score(y_actual_cls, y_pred_cls)

# Compute recall manually
recall_manual = np.diag(conf_matrix) / np.sum(conf_matrix, axis=1)

# Compute recall using sklearn
recall_lib = recall_score(y_actual_cls, y_pred_cls, average=None)

# Print results
print(f"MAE calculated manually: {mae_manual}")
print(f"MAE using library: {mae_library}")
print(f"RMSE calculated manually: {rmse_manual}")
print(f"RMSE using library: {rmse_library}")
print("Confusion Matrix calculated manually:")
print(conf_matrix)
print("Confusion Matrix using library:")
print(conf_matrix_lib)
print(f"Accuracy calculated manually: {accuracy_manual}")
print(f"Accuracy using library: {accuracy_lib}")
print(f"Recall calculated manually: {recall_manual}")
print(f"Recall using library: {recall_lib}")


MAE calculated manually: 0.40000000000000124
MAE using library: 0.40000000000000124
RMSE calculated manually: 0.4301162633521323
RMSE using library: 0.4301162633521323
Confusion Matrix calculated manually:
[[3 2]
 [2 3]]
Confusion Matrix using library:
[[3 2]
 [2 3]]
Accuracy calculated manually: 0.6
Accuracy using library: 0.6
Recall calculated manually: [0.6 0.6]
Recall using library: [0.6 0.6]


In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, confusion_matrix, accuracy_score, recall_score, f1_score

# Actual and predicted values for regression
y_actual = np.array([20, 30, 40, 50])
y_pred = np.array([20.5, 30.3, 40.2, 50.6])

# Calculate MAE from scratch
mae_manual = np.sum(np.abs(y_actual - y_pred)) / len(y_actual)

# Calculate MAE using sklearn
mae_library = mean_absolute_error(y_actual, y_pred)

# Calculate RMSE from scratch
rmse_manual = np.sqrt(np.sum((y_actual - y_pred) ** 2) / len(y_actual))

# Calculate RMSE using sklearn
rmse_library = np.sqrt(mean_squared_error(y_actual, y_pred))

# Actual and predicted values for classification (Table 8)
y_actual_cls = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
y_pred_cls = np.array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1])

# Compute confusion matrix manually
num_classes = len(np.unique(y_actual_cls))
conf_matrix = np.zeros((num_classes, num_classes), dtype=int)
for a, p in zip(y_actual_cls, y_pred_cls):
    conf_matrix[a, p] += 1

# Compute confusion matrix using sklearn
conf_matrix_lib = confusion_matrix(y_actual_cls, y_pred_cls)

# Compute accuracy manually
accuracy_manual = np.sum(np.diag(conf_matrix)) / len(y_actual_cls)

# Compute accuracy using sklearn
accuracy_lib = accuracy_score(y_actual_cls, y_pred_cls)

# Compute recall manually
recall_manual = np.diag(conf_matrix) / np.sum(conf_matrix, axis=1)

# Compute recall using sklearn
recall_lib = recall_score(y_actual_cls, y_pred_cls, average=None)

# Compute F1-score manually
precision_manual = np.diag(conf_matrix) / np.sum(conf_matrix, axis=0)
f1_manual = 2 * (precision_manual * recall_manual) / (precision_manual + recall_manual)

# Compute F1-score using sklearn
f1_lib = f1_score(y_actual_cls, y_pred_cls, average=None)

# Print results
print(f"MAE calculated manually: {mae_manual}")
print(f"MAE using library: {mae_library}")
print(f"RMSE calculated manually: {rmse_manual}")
print(f"RMSE using library: {rmse_library}")
print("Confusion Matrix calculated manually:")
print(conf_matrix)
print("Confusion Matrix using library:")
print(conf_matrix_lib)
print(f"Accuracy calculated manually: {accuracy_manual}")
print(f"Accuracy using library: {accuracy_lib}")
print(f"Recall calculated manually: {recall_manual}")
print(f"Recall using library: {recall_lib}")
print(f"F1-score calculated manually: {f1_manual}")
print(f"F1-score using library: {f1_lib}")


MAE calculated manually: 0.40000000000000124
MAE using library: 0.40000000000000124
RMSE calculated manually: 0.4301162633521323
RMSE using library: 0.4301162633521323
Confusion Matrix calculated manually:
[[3 2]
 [2 3]]
Confusion Matrix using library:
[[3 2]
 [2 3]]
Accuracy calculated manually: 0.6
Accuracy using library: 0.6
Recall calculated manually: [0.6 0.6]
Recall using library: [0.6 0.6]
F1-score calculated manually: [0.6 0.6]
F1-score using library: [0.6 0.6]


In [ ]:
import numpy as np
from scipy.optimize import linprog
from sklearn.metrics import mean_absolute_error, mean_squared_error, confusion_matrix, accuracy_score, recall_score, f1_score

# Actual and predicted values for regression
y_actual = np.array([20, 30, 40, 50])
y_pred = np.array([20.5, 30.3, 40.2, 50.6])

# Calculate MAE from scratch
mae_manual = np.sum(np.abs(y_actual - y_pred)) / len(y_actual)

# Calculate MAE using sklearn
mae_library = mean_absolute_error(y_actual, y_pred)

# Calculate RMSE from scratch
rmse_manual = np.sqrt(np.sum((y_actual - y_pred) ** 2) / len(y_actual))

# Calculate RMSE using sklearn
rmse_library = np.sqrt(mean_squared_error(y_actual, y_pred))

# Actual and predicted values for classification (Table 8)
y_actual_cls = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
y_pred_cls = np.array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1])

# Compute confusion matrix manually
num_classes = len(np.unique(y_actual_cls))
conf_matrix = np.zeros((num_classes, num_classes), dtype=int)
for a, p in zip(y_actual_cls, y_pred_cls):
    conf_matrix[a, p] += 1

# Compute confusion matrix using sklearn
conf_matrix_lib = confusion_matrix(y_actual_cls, y_pred_cls)

# Compute accuracy manually
accuracy_manual = np.sum(np.diag(conf_matrix)) / len(y_actual_cls)

# Compute accuracy using sklearn
accuracy_lib = accuracy_score(y_actual_cls, y_pred_cls)

# Compute recall manually
recall_manual = np.diag(conf_matrix) / np.sum(conf_matrix, axis=1)

# Compute recall using sklearn
recall_lib = recall_score(y_actual_cls, y_pred_cls, average=None)

# Compute F1-score manually
precision_manual = np.diag(conf_matrix) / np.sum(conf_matrix, axis=0)
f1_manual = 2 * (precision_manual * recall_manual) / (precision_manual + recall_manual)

# Compute F1-score using sklearn
f1_lib = f1_score(y_actual_cls, y_pred_cls, average=None)

# Solve Linear Programming Problem with Three Variables
c = [-4, -5, -6]  # Coefficients for maximization (negated for linprog)
A = [[2, 1, 1], [4, 3, 0]]  # Coefficients for inequality constraints
b = [14, 20]  # Right-hand side values of inequalities
bounds = [(0, None), (0, None), (0, None)]  # Non-negative constraints

result = linprog(c, A_ub=A, b_ub=b, bounds=bounds, method='highs')

# Print results
print(f"MAE calculated manually: {mae_manual}")
print(f"MAE using library: {mae_library}")
print(f"RMSE calculated manually: {rmse_manual}")
print(f"RMSE using library: {rmse_library}")
print("Confusion Matrix calculated manually:")
print(conf_matrix)
print("Confusion Matrix using library:")
print(conf_matrix_lib)
print(f"Accuracy calculated manually: {accuracy_manual}")
print(f"Accuracy using library: {accuracy_lib}")
print(f"Recall calculated manually: {recall_manual}")
print(f"Recall using library: {recall_lib}")
print(f"F1-score calculated manually: {f1_manual}")
print(f"F1-score using library: {f1_lib}")
print("Linear Programming Solution:")
print(f"Optimal values for X, Y, Z: {result.x}")
print(f"Maximum value of P: {-result.fun}")


MAE calculated manually: 0.40000000000000124
MAE using library: 0.40000000000000124
RMSE calculated manually: 0.4301162633521323
RMSE using library: 0.4301162633521323
Confusion Matrix calculated manually:
[[3 2]
 [2 3]]
Confusion Matrix using library:
[[3 2]
 [2 3]]
Accuracy calculated manually: 0.6
Accuracy using library: 0.6
Recall calculated manually: [0.6 0.6]
Recall using library: [0.6 0.6]
F1-score calculated manually: [0.6 0.6]
F1-score using library: [0.6 0.6]
Linear Programming Solution:
Optimal values for X, Y, Z: [ 0.  0. 14.]
Maximum value of P: 84.0


In [ ]:
import numpy as np
from scipy.optimize import linprog
from sklearn.metrics import mean_absolute_error, mean_squared_error, confusion_matrix, accuracy_score, recall_score, f1_score

# Actual and predicted values for regression
y_actual = np.array([20, 30, 40, 50])
y_pred = np.array([20.5, 30.3, 40.2, 50.6])

# Calculate MAE from scratch
mae_manual = np.sum(np.abs(y_actual - y_pred)) / len(y_actual)

# Calculate MAE using sklearn
mae_library = mean_absolute_error(y_actual, y_pred)

# Calculate RMSE from scratch
rmse_manual = np.sqrt(np.sum((y_actual - y_pred) ** 2) / len(y_actual))

# Calculate RMSE using sklearn
rmse_library = np.sqrt(mean_squared_error(y_actual, y_pred))

# Actual and predicted values for classification (Table 8)
y_actual_cls = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
y_pred_cls = np.array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1])

# Compute confusion matrix manually
num_classes = len(np.unique(y_actual_cls))
conf_matrix = np.zeros((num_classes, num_classes), dtype=int)
for a, p in zip(y_actual_cls, y_pred_cls):
    conf_matrix[a, p] += 1

# Compute confusion matrix using sklearn
conf_matrix_lib = confusion_matrix(y_actual_cls, y_pred_cls)

# Compute accuracy manually
accuracy_manual = np.sum(np.diag(conf_matrix)) / len(y_actual_cls)

# Compute accuracy using sklearn
accuracy_lib = accuracy_score(y_actual_cls, y_pred_cls)

# Compute recall manually
recall_manual = np.diag(conf_matrix) / np.sum(conf_matrix, axis=1)

# Compute recall using sklearn
recall_lib = recall_score(y_actual_cls, y_pred_cls, average=None)

# Compute F1-score manually
precision_manual = np.diag(conf_matrix) / np.sum(conf_matrix, axis=0)
f1_manual = 2 * (precision_manual * recall_manual) / (precision_manual + recall_manual)

# Compute F1-score using sklearn
f1_lib = f1_score(y_actual_cls, y_pred_cls, average=None)

# Solve Linear Programming Problem with Three Variables (New problem)
c = [-40, -30]  # Coefficients for maximization (negated for linprog)
A = [[1, 2], [2, 3]]  # Coefficients for inequality constraints
b = [40, 60]  # Right-hand side values of inequalities
bounds = [(0, None), (0, None)]  # Non-negative constraints

result = linprog(c, A_ub=A, b_ub=b, bounds=bounds, method='highs')

# Print results
print(f"MAE calculated manually: {mae_manual}")
print(f"MAE using library: {mae_library}")
print(f"RMSE calculated manually: {rmse_manual}")
print(f"RMSE using library: {rmse_library}")
print("Confusion Matrix calculated manually:")
print(conf_matrix)
print("Confusion Matrix using library:")
print(conf_matrix_lib)
print(f"Accuracy calculated manually: {accuracy_manual}")
print(f"Accuracy using library: {accuracy_lib}")
print(f"Recall calculated manually: {recall_manual}")
print(f"Recall using library: {recall_lib}")
print(f"F1-score calculated manually: {f1_manual}")
print(f"F1-score using library: {f1_lib}")
print("Linear Programming Solution:")
print(f"Optimal values for A, B: {result.x}")
print(f"Maximum value of P: {-result.fun}")


MAE calculated manually: 0.40000000000000124
MAE using library: 0.40000000000000124
RMSE calculated manually: 0.4301162633521323
RMSE using library: 0.4301162633521323
Confusion Matrix calculated manually:
[[3 2]
 [2 3]]
Confusion Matrix using library:
[[3 2]
 [2 3]]
Accuracy calculated manually: 0.6
Accuracy using library: 0.6
Recall calculated manually: [0.6 0.6]
Recall using library: [0.6 0.6]
F1-score calculated manually: [0.6 0.6]
F1-score using library: [0.6 0.6]
Linear Programming Solution:
Optimal values for A, B: [30.  0.]
Maximum value of P: 1200.0
